// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChviD42B5mZsL5p9MESb7lrLG6SmzGfFc',
    appId: '1:1017299149035:web:9be88d4de060d4fa6f1eae',
    messagingSenderId: '1017299149035',
    projectId: 'setec-front',
    authDomain: 'setec-front.firebaseapp.com',
    storageBucket: 'setec-front.firebasestorage.app',
    measurementId: 'G-QTM25KMHPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFPr2oKagDSvI24Xxq_OBlzihJEaX8pjw',
    appId: '1:1017299149035:android:359f77c6ad9024796f1eae',
    messagingSenderId: '1017299149035',
    projectId: 'setec-front',
    storageBucket: 'setec-front.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArHs4Hmc48rOcGWazkwSjBTZwcjdDanM8',
    appId: '1:1017299149035:ios:3a2de73935dea29b6f1eae',
    messagingSenderId: '1017299149035',
    projectId: 'setec-front',
    storageBucket: 'setec-front.firebasestorage.app',
    iosClientId: '1017299149035-biugv40fjsq69qre4dtsl5dpcs7ahj2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.setecApp',
  );
}
