name: setec_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  lint: ^2.3.0
  sign_in_button: ^3.2.0
  provider: ^6.1.2
  logger: ^2.5.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  go_router: ^14.7.2
  collection: ^1.18.0
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  intl: ^0.20.2
  freezed_annotation: ^3.0.0
  dio: ^5.8.0+1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
dev_dependencies:
  freezed: ^3.0.6
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
